authApp/urls.py
from django.urls import path
from . import views
app_name = 'authApp'
urlpatterns = [
	path('signup/',views.sign_up, name='signup' ),
	path('login/', views.log_in, name='login'),
	path('signup_success/', views.register_user, name='register_user'),
	path('login', views.authenticate_user, name='authenticate_user'),
]

doseTrackerPrj/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('doseage-tracker/', include('authApp.urls')),
    path('doseage-tracker/', include('mainApp.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainApp/urls.py
from django.urls import path
from . import views

app_name = "mainApp"
urlpatterns = [
    path("dashboard/<str:username>", views.index, name="index"),
    path("logout", views.logout_user, name="logout_user"),
    path("profile/<str:username>", views.show_new_form, name="show_new_form"),
    path("dosage_created", views.create_dosage, name="create_dosage"),
    path("delete/<int:dosage_id>", views.delete_dosage, name="delete_dosage"),
    path("edit/<int:dosage_id>/", views.edit_dosage, name="edit_dosage"),
]

mainApp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Dosage(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='dosages')
    medicine_name = models.CharField(max_length=100,blank=False)
    quantity = models.IntegerField(blank=False)
    units = models.CharField(max_length=50, blank=False)
    frequency = models.CharField(max_length=50, blank=False)
    
    def __str__(self) -> str:
        return self.medicine_name

mainApp/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Submit, HTML
from django.urls import reverse


class DosageForm(forms.Form):
    medicine_name = forms.CharField(label="MedicineName", required=True, max_length=50)
    quantity = forms.CharField(label="Quantity", required=True, max_length=50)
    units = forms.CharField(label="Units", required=True, max_length=100)
    frequency = forms.CharField(label="Frequency", required=True, max_length=50)

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = user
        self.helper = FormHelper()
        self.helper.form_method = "POST"
        self.helper.form_action = reverse("mainApp:create_dosage")
        self.helper.form_class = ""
        self.helper.layout = Layout(
            Div("medicine_name", "quantity", "units", "frequency"),
            Div(
                HTML(
                    """ <a
            href="{% url 'mainApp:logout_user' %}"
            class="w-1/2 text-center bg-red-600 text-white py-2 rounded-md hover:bg-red-500 focus:outline-none"
            >Logout</a
        >
         <a
            href="{% url 'mainApp:index' username=user  %}"
            class="w-1/2 text-center bg-blue-600 text-white py-2 rounded-md hover:bg-blue-500 focus:outline-none"
            >View Existing Data</a
        >
        """
                ),
                css_class="mt-6 flex justify-between",
            ),
            Div(
                Submit(
                    "submit",
                    "Submit",
                    css_class='w-full mt-4 text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800"',
                ),
                css_class="max-w-full",
            ),
        )

mainApp/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from .forms import DosageForm
from .models import Dosage
from authApp.models import ProfilePic
from django.contrib.auth.models import User


# Create your views here.
@login_required(login_url="authApp:login")
def index(request, username):
    username = request.user
    dosages = Dosage.objects.filter(user=username)
    # a = dosages.username

    return render(
        request,
        "dosages_list.html",
        {"dosage": dosages},
    )


def logout_user(request):
    logout(request)
    return redirect("authApp:login")


def create_dosage(request):
    username = request.user

    if request.method == "POST":
        medicine_name = request.POST["medicine_name"]
        quantity = request.POST["quantity"]
        units = request.POST["units"]
        frequency = request.POST["frequency"]

    new_dosage = Dosage(
        user=username,
        medicine_name=medicine_name,
        quantity=quantity,
        units=units,
        frequency=frequency,
    )
    new_dosage.save()

    return redirect("mainApp:index", username=username)


@login_required(login_url="authApp:login")
def delete_dosage(request, dosage_id):
    username = request.user
    dosage = Dosage.objects.filter(pk=dosage_id)
    dosage.delete()
    return redirect("mainApp:index", username=username)


def edit_dosage(request, dosage_id):
    username = request.user
    # dosage = Dosage.objects.get(user=username)
    dosage = get_object_or_404(Dosage, id=dosage_id)
    if request.method == "POST":
        new_medicine_name = request.POST.get("editName")
        new_quantity = request.POST.get("editQuantity")
        new_units = request.POST.get("editUnit")
        new_frequency = request.POST.get("editFrequency")

        if new_medicine_name and new_quantity and new_units and new_frequency:
            dosage.medicine_name = new_medicine_name
            dosage.quantity = new_quantity
            dosage.units = new_units
            dosage.frequency = new_frequency
            dosage.save()
            return redirect("mainApp:index", username=request.user.username)
        else:
            return redirect("mainApp:index", username=request.user.username)

    return redirect("mainApp:index", username=username)


@login_required(login_url="authApp:login")
def show_new_form(request, username):
    form = DosageForm(username)
    return render(request, "index.html", {"form": form, "username": username})

mainApp/templates/dosages_list.html
{% extends 'base.html' %} {% block content %} {% include 'profile.html' %}

<div class="container mx-auto">
    <h1 class="text-2xl font-bold mb-4">Medicine List</h1>

    <ul class="bg-white shadow-md rounded-lg">
        {% for dosage in dosages %}
        <li
            class="flex justify-between items-center border-b p-4 hover:bg-gray-50"
        >
            <div class="flex flex-col">
                <span class="font-semibold"
                    >Medicine Name: {{dosage.medicine_name}}</span
                >
                <span>Unit: {{dosage.units}}</span>
                <span>Frequency: {{dosage.frequency}}</span>
                <span>Quantity: {{dosage.quantity}}</span>
            </div>
            <div>
                <button
                    onclick="openModal()"
                    class="bg-blue-500 text-white px-4 py-2 rounded-md hover:bg-blue-600"
                    data-id="{{dosage.id}}"
                >
                    Edit
                </button>
                <a
                    href="{% url 'mainApp:delete_dosage' dosage.id %}"
                    class="bg-red-500 text-white px-4 py-2 rounded-md hover:bg-red-600 ml-2"
                >
                    Delete
                </a>
            </div>
        </li>
        <div id="modal" class="modal">
            <div class="bg-white rounded-lg shadow-lg p-6 w-96">
                <h2 class="text-xl font-bold mb-4">Edit Medicine</h2>
                <form
                    method="post"
                    action='{% url "mainApp:edit_dosage" dosage.id %}'
                >
                    {% csrf_token %}
                    <label class="block mb-2">
                        Medicine Name:
                        <input
                            name="editName"
                            type="text"
                            class="border rounded-md p-2 w-full"
                            placeholder="Enter medicine name"
                            value="{{dosage.medicine_name}}"
                            required
                        />
                    </label>
                    <label class="block mb-2">
                        Unit:
                        <input
                            name="editUnit"
                            type="text"
                            class="border rounded-md p-2 w-full"
                            placeholder="Enter unit"
                            value="{{dosage.units}}"
                            required
                        />
                    </label>
                    <label class="block mb-2">
                        Frequency:
                        <input
                            name="editFrequency"
                            type="text"
                            class="border rounded-md p-2 w-full"
                            placeholder="Enter frequency"
                            value="{{dosage.frequency}}"
                            required
                        />
                    </label>
                    <label class="block mb-2">
                        Quantity:
                        <input
                            name="editQuantity"
                            type="number"
                            class="border rounded-md p-2 w-full"
                            placeholder="Enter quantity"
                            value="{{dosage.quantity}}"
                            required
                        />
                    </label>
                    <div class="mt-4 flex justify-end">
                        <button
                            type="button"
                            onclick="closeModal()"
                            class="bg-gray-500 text-white px-4 py-2 rounded-md mr-2"
                        >
                            Close
                        </button>
                        <button
                            type="submit"
                            class="bg-blue-500 text-white px-4 py-2 rounded-md"
                        >
                            Save
                        </button>
                    </div>
                </form>
            </div>
        </div>
        {% endfor %}

        <!-- Add more list items as needed -->
    </ul>
</div>
<!-- Modal -->

{% endblock content %}

mainApp/templates/index.html
{% extends 'base.html' %} {% load crispy_forms_tags %} {% block content %}
<h1></h1>
{% include 'profile.html' %}
<div class="max-w-md mx-auto mt-10 p-6 bg-white rounded-lg shadow-md">
    <h2 class="text-2xl font-semibold mb-6">Medicine Dose Tracker</h2>
    {% crispy form %} {% csrf_token %}
</div>

{% endblock %}

mainApp/templates/profile.html
<div class="container mx-auto flex items-center mb-6">
    <div class="w-16 h-16 rounded-full overflow-hidden mr-4">
        <!-- Profile picture -->
        <img
            src="{{profile_pic}}"
            alt="Profile Picture"
            class="w-full h-full object-cover"
            id="profile_picture"
        />
    </div>
    <div>
        <!-- Username -->
        <h1 class="text-xl font-bold" id="username">{{username}}</h1>
        <p class="text-gray-600">Your Medicine Tracker</p>
    </div>
    <a
        href="{% url 'mainApp:logout_user' %}"
        class="text-center bg-red-600 text-white py-2 rounded-md hover:bg-red-500 focus:outline-none"
        >Logout</a
    >
    <a
        href="{% url 'mainApp:show_new_form' username=user %}"
        class="text-center bg-red-600 text-white py-2 rounded-md hover:bg-red-500 focus:outline-none"
        >Add new</a
    >
</div>